// <auto-generated />
using System;
using CheckoutKata.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CheckoutKata.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CheckoutKata.Shared.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "N/A",
                            Image = "https://via.placeholder.com/300x300",
                            Price = 10m,
                            Title = "A"
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "N/A",
                            Image = "https://via.placeholder.com/300x300",
                            Price = 15m,
                            Title = "B"
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "N/A",
                            Image = "https://via.placeholder.com/300x300",
                            Price = 40m,
                            Title = "C"
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "N/A",
                            Image = "https://via.placeholder.com/300x300",
                            Price = 55m,
                            Title = "D"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
